name: Build and Deploy Resume
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install LaTeX
        run: |
          echo "Updating package lists..."
          sudo apt-get update
          echo "Installing LaTeX..."
          sudo apt-get install -y texlive-full

      - name: Build PDF
        run: |
          echo "Building PDF from LaTeX source..."
          pdflatex Nicholas_Tietje_Resume.tex
          echo "PDF built successfully: Nicholas_Tietje_Resume.pdf"

      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume-pdf
          path: Nicholas_Tietje_Resume.pdf

      # - name: Commit to the output branch of repo
      #   run: |
      #     echo "Configuring Git user..."
      #     git config --global user.name "github-stats[bot]"
      #     git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     echo "Adding generated PDF to Git..."
      #     git add Nicholas_Tietje_Resume.pdf
      #     git commit -m 'temp commit' || echo "No changes to commit."
      #     git checkout output 2>/dev/null || git checkout --orphan output && git rm -rf . && git checkout main -- Nicholas_Tietje_Resume.pdf
      #     git commit -m 'Update generated files' || echo "No changes to commit."
      #     echo "Pushing changes to output branch..."
      #     git push origin output -f

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download resume artifact
        uses: actions/download-artifact@v3
        with:
          name: resume-pdf

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381492274117:role/github-actions-role
          aws-region: us-east-1
          role-session-name: github-oidc-session

      - name: Install AWS CLI
        run: |
          echo "Installing AWS CLI..."
          sudo apt-get install -y awscli

      - name: Upload PDF to S3
        env:
          S3_BUCKET: your-s3-bucket-name
          S3_KEY: Nicholas_Tietje_Resume.pdf
        run: |
          echo "Uploading PDF to S3..."
          aws s3 cp Nicholas_Tietje_Resume.pdf s3://tietje-resume-bucket/Nicholas_Tietje_Resume.pdf
          echo "Upload completed."

      - name: Verify S3 Upload
        env:
          S3_BUCKET: your-s3-bucket-name
          S3_KEY: Nicholas_Tietje_Resume.pdf
        run: |
          echo "Verifying upload to S3..."
          if aws s3 ls s3://tietje-resume-bucket/Nicholas_Tietje_Resume.pdf; then
            echo "File exists in S3."
          else
            echo "File does not exist in S3."
            exit 1
          fi
